### ISSUE TITLE
What are the ruby commands for all the commands shown

### ISSUE THREAD

**Issue by stephen147** [thomthom/cleanup#19]
I'm trying to add a toolbar with these items using the toolbar editor: https://extensions.sketchup.com/extension/e413511f-0517-4115-8d81-90039a20a72c/toolbar-editor

So I was trying to create one for cleanup but there are no buttons that can be added, so I was wondering what the ruby commands are for these?

![image](https://user-images.githubusercontent.com/14054664/77187178-f7694c80-6acb-11ea-940e-a1fc53b230e1.png)

**Comment by thomthom** [comment]
Have a look at these lines that defines the menu item:
https://github.com/thomthom/cleanup/blob/eaa4050c7f34d311ae59b50047d07e9f5ef63d2e/src/tt_cleanup/core.rb#L233-L241

**Comment by stephen147** [comment]
I cannot seem to get it to work. How to I point to `show_cleanup_ui`.

I've tried using `{ show_cleanup_ui }` but I'm not familiar with the syntax required.

**Comment by thomthom** [comment]
When calling them from an external namespace you need to use their fully qualified names:

```ruby
TT::Plugins::CleanUp.cu_erase_hidden
TT::Plugins::CleanUp.cu_erase_lonely_edges
TT::Plugins::CleanUp.cu_geom2layer0
TT::Plugins::CleanUp.cu_merge_faces
TT::Plugins::CleanUp.cu_merge_materials
TT::Plugins::CleanUp.cu_repair_edges
```

**Comment by stephen147** [comment]
Thanks very much, that will allow me to add just the ones I wanted to the toolbar.

**Comment by stephen147** [comment]
I've created a set of icons for CU in case anyone wants to do the same.

![image](https://user-images.githubusercontent.com/14054664/77233101-2996af00-6b9d-11ea-8428-edc1c54815b2.png)


[icons.zip](https://github.com/thomthom/cleanup/files/4363579/icons.zip)
