### ISSUE TITLE
Cleanup 3 crashes following latest update. (2/22/24)

### ISSUE THREAD

**Issue by jdkoll66** [thomthom/cleanup#21]
Get this crash message since updating Cleanup3 and TT-lib. Running Sketchup 2023.

![Capture](https://github.com/thomthom/cleanup/assets/45979057/f50c6c84-9a97-4fcd-83ef-6ef25ed8733c)

**Comment by thomthom** [comment]
Ooops! I'll get that fixed. Thank you for reporting.

**Comment by jdkoll66** [comment]
Thanks for the quick fix!
    On Thursday, February 22, 2024 at 02:42:58 PM EST, Thomas Thomassen ***@***.***> wrote:  
 
 


This is now live on Extension Warehouse and SketchUcation.
